// shared student database for both student portal and admin dashboard
const students = [
    // --- 61st Batch ---
    { name: "Deva", pass: "1371", batch: "61st" },
    { name: "Nikhil", pass: "3272", batch: "61st" },
    { name: "Dimpal", pass: "3321", batch: "61st" },
    { name: "Tanuja", pass: "3346", batch: "61st" },
    { name: "Samruddhi", pass: "3270", batch: "61st" },
    { name: "Kartiki", pass: "3351", batch: "61st" },
    { name: "Hitesh", pass: "2685", batch: "61st" },
    { name: "Saurabh Shivaji Bhoir", pass: "3252", batch: "61st" },
    { name: "Soham Mahendra Chaudhari", pass: "3261", batch: "61st" },
    { name: "Shreya Sharad Dabhade", pass: "3263", batch: "61st" },
    { name: "Ruchita Pandurang Farde", pass: "3271", batch: "61st" },
    { name: "Mithil Jitendra Gawde", pass: "3274", batch: "61st" },
    { name: "Swapnil Jotiram Jambhale", pass: "3281", batch: "61st" },
    { name: "Sankit Shivprasad Kahar", pass: "3284", batch: "61st" },
    { name: "Adil Dawood Khan", pass: "3288", batch: "61st" },
    { name: "Nayan Shrikant Kondilkar", pass: "3291", batch: "61st" },
    { name: "Parth Gajanan Kondilkar", pass: "3292", batch: "61st" },
    { name: "Yash Ankush Kumawat", pass: "3294", batch: "61st" },
    { name: "Manas Sunil Lad", pass: "3296", batch: "61st" },
    { name: "Sujit Dinesh Magar", pass: "3299", batch: "61st" },
    { name: "Kunal Pundalik Mahajan", pass: "3301", batch: "61st" },
    { name: "Viraj Dhanaji Malik", pass: "3302", batch: "61st" },
    { name: "Tejas Ganpat Padwal", pass: "3311", batch: "61st" },
    { name: "Yadnyesh Prakash Partole", pass: "3313", batch: "61st" },
    { name: "Harsh Ganesh Patil", pass: "3314", batch: "61st" },
    { name: "Jitesh Ganesh Rane", pass: "3320", batch: "61st" },
    { name: "Dimpal Subhash Rasal", pass: "3321", batch: "61st" },
    { name: "Kasturi Kiran Shingate", pass: "3329", batch: "61st" },
    { name: "Daksh Prabhakar Sonawane", pass: "3330", batch: "61st" },
    { name: "Payal Tatya Suryavanshi", pass: "3334", batch: "61st" },
    { name: "Samadhan Sitaram Suryavanshi", pass: "3335", batch: "61st" },
    { name: "Pramita Gautam Vavhal", pass: "3340", batch: "61st" },
    { name: "Bhushan Gurunath Vishe", pass: "3341", batch: "61st" },
    { name: "Om Dinesh Vishe", pass: "3342", batch: "61st" },
    { name: "Shriraj Nitin Wadkar", pass: "3344", batch: "61st" },
    { name: "Ragini Shivnath Jaiswar", pass: "3355", batch: "61st" },
    { name: "Sarthak Dattatray", pass: "3246", batch: "61st" },
    { name: "Paras Bhagwan", pass: "3251", batch: "61st" },
    { name: "Aryan Sameer", pass: "3257", batch: "61st" },
    { name: "Nayan Ashok", pass: "3258", batch: "61st" },
    { name: "Sayali Mahadev", pass: "3276", batch: "61st" },
    { name: "Palak Raghav", pass: "3278", batch: "61st" },
    { name: "Renuka Kailas", pass: "3283", batch: "61st" },
    { name: "Nikhil Pradip", pass: "3285", batch: "61st" },
    { name: "Ved Arun Kawale", pass: "3286", batch: "61st" },
    { name: "Shivani Sharad", pass: "3287", batch: "61st" },
    { name: "Nishant Bharat", pass: "3289", batch: "61st" },
    { name: "Tanmay Mahendra", pass: "3293", batch: "61st" },
    { name: "Raj Ramkrit", pass: "3295", batch: "61st" },
    { name: "Aryan Ganpat", pass: "3303", batch: "61st" },
    { name: "Vighnesh Suryakan", pass: "3306", batch: "61st" },
    { name: "Teju Deepak", pass: "3316", batch: "61st" },
    { name: "Dhiraj Anil", pass: "3317", batch: "61st" },
    { name: "Anagha Hanumat", pass: "3323", batch: "61st" },
    { name: "Indra Arun", pass: "3324", batch: "61st" },
    { name: "Aryan Anil", pass: "3328", batch: "61st" },
    { name: "Sandesh Bapu Sor", pass: "3331", batch: "61st" },
    { name: "Khushali Sainath", pass: "3332", batch: "61st" },
    { name: "Rishabh Santosh", pass: "3333", batch: "61st" },
    { name: "Siddhesh Sopan", pass: "3336", batch: "61st" },
    { name: "Shivam Sachin", pass: "3337", batch: "61st" },
    { name: "Ashish Ganesh", pass: "3343", batch: "61st" },
    { name: "Shravan Wadkar", pass: "3345", batch: "61st" },
    { name: "Yash Sharad", pass: "3348", batch: "61st" },
    { name: "Jayshree Vasant", pass: "3352", batch: "61st" },
    { name: "Purva Panchal", pass: "3356", batch: "61st" },

    // --- 62nd Batch ---
    { name: "Antara Vishwas", pass: "3376", batch: "62nd" },
    { name: "Deva", pass: "1371", batch: "62nd" },
    { name: "Dhammapal", pass: "3388", batch: "62nd" },
    { name: "Hitesh", pass: "2685", batch: "62nd" },
    { name: "Yadnya", pass: "3468", batch: "62nd" },
    { name: "Samruddhi", pass: "3270", batch: "62nd" },
    { name: "Kartiki", pass: "3351", batch: "62nd" },
    { name: "Harshada", pass: "3399", batch: "62nd" },
    { name: "Bhavesh B", pass: "3380", batch: "62nd" },
    { name: "Chirag Vir", pass: "3385", batch: "62nd" },
    { name: "Darshan K", pass: "3386", batch: "62nd" },
    { name: "Dhamma P", pass: "3388", batch: "62nd" },
    { name: "Dinesh M", pass: "3390", batch: "62nd" },
    { name: "Harshad K", pass: "3398", batch: "62nd" },
    { name: "Jagruti Madhukar", pass: "3402", batch: "62nd" },
    { name: "Jaykumar", pass: "3405", batch: "62nd" },
    { name: "Karan Dal", pass: "3407", batch: "62nd" },
    { name: "Lalit Pruth", pass: "3413", batch: "62nd" },
    { name: "Niyati Kamli", pass: "3417", batch: "62nd" },
    { name: "Parth Pre", pass: "3419", batch: "62nd" },
    { name: "Pradnya S", pass: "3422", batch: "62nd" },
    { name: "Pranjal Ut", pass: "3423", batch: "62nd" },
    { name: "Prathamesh", pass: "3426", batch: "62nd" },
    { name: "Prathmesh", pass: "3427", batch: "62nd" },
    { name: "Rajesh Ball", pass: "3429", batch: "62nd" },
    { name: "Ruksana B", pass: "3431", batch: "62nd" },
    { name: "Samiksha", pass: "3435", batch: "62nd" },
    { name: "Samiksha", pass: "3436", batch: "62nd" },
    { name: "Sanskruti", pass: "3439", batch: "62nd" },
    { name: "Sarvesh V", pass: "3442", batch: "62nd" },
    { name: "Sayali Sut", pass: "3443", batch: "62nd" },
    { name: "Sharda Pr", pass: "3444", batch: "62nd" },
    { name: "Sushant N", pass: "3453", batch: "62nd" },
    { name: "Tejaswini", pass: "3458", batch: "62nd" },
    { name: "Vaibhavi F", pass: "3460", batch: "62nd" },
    { name: "Vedant Vi", pass: "3464", batch: "62nd" },
    { name: "Vedika Sa", pass: "3465", batch: "62nd" },
    { name: "Velvin Vis", pass: "3466", batch: "62nd" },
    { name: "Yadanya M", pass: "3468", batch: "62nd" },
    { name: "Yashraj D", pass: "3472", batch: "62nd" },
    { name: "Kirti Kisho", pass: "3474", batch: "62nd" },
    { name: "Vedika Vishwas Egade", pass: "3478", batch: "62nd" },
    { name: "Bhagyashree Sachin Ghude", pass: "3379", batch: "62nd" },
    { name: "Bhavika Anil Late", pass: "3382", batch: "62nd" },
    { name: "Dipti Yashwant Gund", pass: "3391", batch: "62nd" },
    { name: "Durvesh Kiran Ambekar", pass: "3392", batch: "62nd" },
    { name: "Durvesh Liladhar Madhavi", pass: "3393", batch: "62nd" },
    { name: "Gayatri Balakrishna Bhoir", pass: "3396", batch: "62nd" },
    { name: "Harsh Vasant Gawale", pass: "3397", batch: "62nd" },
    { name: "Harshad Nandkumar Rane", pass: "3399", batch: "62nd" },
    { name: "Jayesh Vekhande", pass: "3404", batch: "62nd" },
    { name: "Kaushik Vikas Chaudhari", pass: "3410", batch: "62nd" },
    { name: "Kunal Narayan Padwal", pass: "3412", batch: "62nd" },
    { name: "Lavanya Bharat Vishe", pass: "3414", batch: "62nd" },
    { name: "Mayuresh Mangesh Bane", pass: "3415", batch: "62nd" },
    { name: "Omkar Ashok Vishe", pass: "3418", batch: "62nd" },
    { name: "Pratibha Bangal", pass: "3420", batch: "62nd" },
    { name: "Piyush Sakharam Madye", pass: "3421", batch: "62nd" },
    { name: "Prashant Vinayak Bangar", pass: "3424", batch: "62nd" },
    { name: "Prathamesh Nitin Shinde", pass: "3425", batch: "62nd" },
    { name: "Riya Sachin Gangawane", pass: "3430", batch: "62nd" },
    { name: "Sakshi Santosh Desale", pass: "3434", batch: "62nd" },
    { name: "Sanika Mahendra Posate", pass: "3437", batch: "62nd" },
    { name: "Sanskruti Ganesh Patange", pass: "3438", batch: "62nd" },
    { name: "Sarthak Santosh Pawar", pass: "3441", batch: "62nd" },
    { name: "Shlok Sunil Patil", pass: "3445", batch: "62nd" },
    { name: "Shreya Sandeep Mane", pass: "3446", batch: "62nd" },
    { name: "Siddhi Santosh Wadavale", pass: "3448", batch: "62nd" },
    { name: "Sourya Mahendra Patle", pass: "3449", batch: "62nd" },
    { name: "Sujata Ravindra Shirke", pass: "3450", batch: "62nd" },
    { name: "Tanuja Shirke", pass: "3457", batch: "62nd" },
    { name: "Unnati Rajendra Suroshe", pass: "3459", batch: "62nd" },
    { name: "Vaishnavi Sitaram Gaikwad", pass: "3461", batch: "62nd" },
    { name: "Vedant Nana Suroshi", pass: "3463", batch: "62nd" },
    { name: "Bhargavi Somnath Bhegade", pass: "3476", batch: "62nd" },
    { name: "Shruti Haresh Gharat", pass: "3477", batch: "62nd" },
    { name: "Nikita Balu Harad", pass: "3479", batch: "62nd" }
];
